templates.scoreModalStudentListTpl = _.template([
    '<section class="modal-window modal_scoreStudentlist">',
        '<section class="form-inline form-wrapper container">',
            '<div class="header-modal-scoreStudentlist">',
                '<span>Student list</span>',
            '</div>',
            '<table class="students_list">',
            '<thead>',
                '<tr>',
                    '<td>Name</td>',
                    '<td>Photo</td>',
                    '<td>Incoming Test</td>',
                    '<td>Entry score</td>',
                    '<td>Approved by</td>',
                '</tr>',
            '</thead>',
            '<tbody class = "tableBodyStudents">',
                '<% _.each(students, function (student) { %>',
                    '<tr>',
                    '<td name="studName"><%= student.name %></td>',
                    '<% if ("avatar" in student ) { %>',
                        '<td><%= student.avatar %></td>',
                    '<% } else { %>',
                        '<td><img class="photo img-circle" src="/img/default-photo.png"/></td>',
                    '<% } %>',
                    '<td><%= student.incomingScore %></td>',
                    '<td><%= student.entryScore %></td>',
                    '<td><%= student.approvedBy %></td>',
                    '</tr>',
                    '<% }); %>',
            '</tdoby>',
            '</table>',
            '<button><i class="fa fa-chevron-left" aria-hidden="true"></i></button>',
            '<button><i class="fa fa-chevron-right" aria-hidden="true"></i></button>',
            '<button class = "fa fa-times-circle-o fa-3x btn-icon exit"></button>',
        '</section>',
    '</section>'
].join(''));