templates.studentCreateTpl = _.template([
    '<section class="modal-window modal_singleStudent">',
        '<section class="form-inline form-wrapper container">',

            '<div class = "row">',
                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                    '<label class = "control-label">Group name</label>',
                    '<input name = "Group name" value = "Dp-099(Web-UI)" class = "form-control" disabled>',
                '</div>',

                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                    '<label class = "control-label">Incoming test</label>',
                    '<input name = "IncomingTest" class = "form-control incomingTest">',
                '</div>',
            '</div>',

            '<div class = "row">',
                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 firstNameInput">',
                    '<label class = "control-label">First name</label>',
                    '<input name = "FirstName" class = "form-control firstName">',
                '</div>',

                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 firstNameInput">',
                    '<label class = "control-label">Entry score</label>',
                    '<input name = "EntryScore" class = "form-control entryScore">',
                '</div>',
            '</div>',

            '<div class = "row">',
                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                    '<label class = "control-label">Last name</label>',
                    '<input name = "LastName" class = "form-control lastName">',
                '</div>',

                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                    '<label class = "control-label">Approved by</label>',
                    '<select class = "form-control approvedBy">',
                      '<option value="Not approved">Not approved</option>',
                      '<option value=Custom>Custom</option>',
                      '<option value="Exptert #1">Exptert #1</option>',
                      '<option value="Exptert #2">Exptert #2</option>',
                      '<option value="Exptert #3">Exptert #3</option>',
                      '<option value="Exptert #4">Exptert #4</option>',
                      '<option value="Exptert #5">Exptert #5</option>',
                    '</select>',
                '</div>',
            '</div>',

            '<div class = "row">',
                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                    '<label class = "control-label">English level</label>',
                    '<select class = "form-control englishLevel">',
                      '<option value="pre-intermediate low">pre-intermediate low</option>',
                      '<option value="pre-intermediate">pre-intermediate</option>',
                      '<option value="pre-intermediate strong">pre-intermediate strong</option>',
                      '<option value="intermediate low">intermediate low</option>',
                      '<option value="intermediate">intermediate</option>',
                      '<option value="intermediate strong">intermediate strong</option>',
                      '<option value="upper-intermediate low">upper-intermediate low</option>',
                      '<option value="upper-intermediate">upper-intermediate</option>',
                      '<option value="upper-intermediate strong">upper-intermediate strong</option>',
                      '<option value="advanced">advanced</option>',
                    '</select>',
                '</div>',

                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                    '<label class = "control-label custom-approval"></label>',
                    '<input name = "CustomApproval" class = "form-control custom-approval-input" disabled>',
                '</div>',
            '</div>',

            '<div class = "row">',
                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                    '<label class = "control-label">CV</label>',

                    '<div class = "pull-right">',
                        '<button class = "BrowseCV form-control btn btn-default active">Browse</button>',
                        '<div class = "downloadedCV hidden">',
                            '<button class = "deleteCV"></button>',
                        '</div>',
                    '</div>',
                '</div>',

                '<div class = "form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                    '<label class = "control-label">Photo</label>',

                    '<div class = "pull-right">',
                        '<button class = "BrowsePhoto form-control btn btn-default active">Browse</button>',
                        '<div class = "downloadedPhoto hidden">',
                            '<button class = "deletePhoto"></button>',
                        '</div>',
                    '</div>',
                '</div>',
            '</div>',

            '<div class = "buttons">',
                '<button class = "save-changes fa fa-check-circle-o fa-3x btn-icon"></button>',
                '<button class = "close-modal-window fa fa-times-circle-o fa-3x btn-icon"></button>',
            '</div>',

        '</section>',
    '</section>',
].join(''));