templates.studentListViewTpl = _.template([
    '<thead>',
        '<tr>',
            '<th class="name">Name</th>',
            '<th>Photo</th>',
            '<th class="range">English level</th>',
        '</tr>',
    '</thead>',
    '<tbody class = "tableBodyStudents">',
        '<% _.each(students, function (student) { %>',
            '<tr>',
            '<td name="studName"><%= student.name %></td>',
            '<% if (student.avatar) { %>',
                '<td><%= student.avatar %></td>',
            '<% } else { %>',
                '<td><img class="photo img-circle" src="/img/default-photo.png"/></td>',
            '<% } %>',
            '<td><%= student.englishLevel %></td>',
            '</tr>',
            '<% }); %>',
    '</tdoby>',
].join(''));