templates.groupEditCreate = _.template([
'    <section class="modal-window <%= isCreate? \'create\' : \'\'%>">',
'                 <section class="form-inline form-wrapper container">',
'                     <div class="row">',
'                         <div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
'                             <div class="row">',
'                                <div class="form-group name-wrapper col-xs-12">',
'                                    <label class="control-label">Group name</label>',
'                                    <input type="text" class="form-control" name="name" value="<%= name %>" tabindex="1">',
'                                    <span class="return-name" hidden></span>',
'                                 </div>',
'                                   <% if (!isCreate) { %>', 
'                                   <div class="form-group col-xs-12 stage-wrapper">',
'                                       <label class="control-label">Current stage</label>',
'                                       <select class="form-control" name="stage" tabindex="2">',
'                                       <% _(stages).each(function(thisStage) { %>',
'                                       <option data-name="stage" value="<%= thisStage %>" <%= thisStage === stage ? \'selected\' : \'\' %> > <%= thisStage %> </option>',
'                                       <% }); %>',
'                                       </select>',
'                                 </div>',
'                                   <% }; %>',
'                               </div>',
'                          </div>',

'                         <div class="form-group budgetOptions col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 ">',
'                             <label class="control-label">Budget owner</label>',
'                             <div class="btn-group pull-right">',
'                                 <button class="btn btn-default budget-option <%= budgetOwner !==  \'OpenGroup\' ? \'active\' : \'\'%>" data-value="SoftServe"  tabindex="10">SoftServe</button>',
'                                 <button class="btn btn-default budget-option <%= budgetOwner ===  \'OpenGroup\' ? \'active\' : \'\'%>" data-value="OpenGroup"  tabindex="11">OpenGroup</button>',
'                             </div>',
'                         </div>',
'                     </div>',

                   ' <hr>',

'                     <div class="row">',
'                         <div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 ">',
'                             <label class="control-label">Direction</label>',
'                             <select class="form-control" name="direction" tabindex="3">',
'                                 <option selected="true" data-name="direction" disabled="disabled"></option>',
'                                 <% _(directions).each(function(thisDirection) { %>',
'                                 <option data-name="direction" value="<%= thisDirection %>" <%= thisDirection === direction ? \'selected\' : \'\' %> > <%= thisDirection %> </option>',
'                                 <% }); %>',
'                             </select>',
'                         </div>',
'                         <div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 calendar-wrapper">',
'                             <label class="control-label">Start date</label>',
'                             <input type="text" class="form-control date-picker" name="startDate" value="<%= startDate %>" placeholder="mm/dd/yyyy"  tabindex="12">',
'                             <span class="fa fa-calendar fa-2x calendar"></span>',
'                        </div>',
'                     </div>',

'                     <div class="row">',
'                         <div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 ">',
'                             <label class="control-label">Location</label>',
'                             <select name="location" class="form-control" tabindex="4" <%= !app.user.isRole(\'Administrator\') ? \'disabled\' : \'\' %> >',
'                                 <% if (!app.user.isRole(\'Administrator\')) { %>',
'                                     <option data-name="location" value="<%= app.user.get(\'location\') %>"><%= app.user.get(\'location\') %></option>',
'                                 <% } else { %>',
'                                     <% _(locations).each(function(thisLocation) { %>',
'                                     <option data-name="location" value="<%= thisLocation %>" <%= (thisLocation === location || thisLocation === defaultLocation) ? \'selected\' : \'\'  %> > <%= thisLocation %> </option>',
'                                     <% }); %>',
'                                 <% } %>',
'                            </select>',
'                         </div>',
'                         <div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 calendar-wrapper">',
'                             <label class="control-label">Finish date</label>',
'                             <input type="text" class="form-control date-picker" name="finishDate" value="<%= finishDate %>" placeholder="mm/dd/yyyy"  tabindex="13">',
'                             <span class="fa fa-calendar fa-2x calendar"></span>',
'                         </div>',
'                     </div>',

'                     <hr>',

'                     <div class="row">',
'                         <div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
'                             <label class="control-label">Teachers</label>',
'                             <div id="teachers" class="pull-right" name="teachers"></div>',
'                         </div>',
'                         <div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 ">',
'                             <label class="control-label">Experts</label>',
'                             <div id="experts" class="pull-right" name="experts"></div>',
'                         </div>',
'                     </div>',

'                     <div class="text-center button-group">',
'                     <span class="fa fa-check-circle-o fa-3x btn-icon" id="save"  tabindex="19"></span>',
'                     <span class="fa fa-times-circle-o fa-3x btn-icon" id="cancel"  tabindex="20"></span></div>',
'                     </div>',
'                </section>',
'             </section>'
].join(''));