templates.groupInfoViewTpl = _.template([
    '<div>',
        '<div class="group_coordination">',
            '<h3>Group coordination:</h3>',
            '<table class="tg">',
                '<tr>',
                    '<th class="tg-h"></th>',
                    '<th class="tg-h"></th>',
                '</tr>',
                    '<% _.each(teachers, function(teacher) { %>',
                        '<tr>',
                        '<td class="tg-d">Teacher</td>',
                        '<td class="tg-d"><%= teacher %></td>',
                        '</tr>',
                    '<% }); %>',
                    '<% _.each(experts, function(expert) { %>',
                        '<tr>',
                        '<td class="tg-d">Expert</td>',
                        '<td class="tg-d"><%= expert %></td>',
                        '</tr>',
                    '<% }); %>',
            '</table>',
        '</div>',
        '<div class="group_info">',
            '<h3>Group info:</h3>',
            '<table class="tg">',
                '<tr>',
                    '<th class="tg-h"></th>',
                    '<th class="tg-h"></th>',
                '</tr>',
                '<tr>',
                    '<td class="tg-d">Date start:</td>',
                    '<td class="tg-d"><%= startDate %></td>',
                '</tr>',
                '<tr>',
                    '<td class="tg-d">Date finish:</td>',
                    '<td class="tg-d"><%= finishDate %></td>',
                '</tr>',
            '</table>',
        '</div>',
    '</div>',
    '<div class="key-dates-container">',
        '<div class="key-dates">',
            '<h3>Key dates:</h3>',
        '</div>',
    '</div>'
].join(''));