templates.groupEditCreate = _.template([
   '<section class="modal-window">',
                '<section class="form-inline form-wrapper container">',
                    '<div class="row">',
                        '<div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 ">',
                            '<label for="groupName" class="control-label">Group name</label>',
                            '<input type="text" class="form-control" id="groupName" name="name" required="required">',
                        '<span class="help-block hidden"></span>',
                       ' </div>',

                        '<div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 ">',
                            '<label for="budgetOptions" class="control-label">Budget owner</label>',
                            '<div class="btn-group pull-right" id="budgetOptions">',
                                '<button class="active btn btn-default budget-option" data-value="SoftServe">SoftServe</button>',
                                '<button class="btn btn-default budget-option" data-value="OpenGroup">OpenGroup</button>',
                            '</div>',
                        '</div>',
                    '</div>',

                   ' <hr>',

                    '<div class="row">',
                        '<div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 ">',
                            '<label for="inputPassword3" class="control-label">Direction</label>',
                           ' <select class="form-control" name="direction" id="inputPassword3">',
                                '<% _(directions).each(function(direction) { %>',
                                '<option data-name="direction" value="<%= direction %>"><%= direction %></option>',
                                '<% }); %>',
                            '</select>',
                        '</div>',
                        '<div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 ">',
                            '<label for="startDate" class="control-label">Start date</label>',
                            '<input type="date" class="form-control" id="startDate" name="startDate">',
    '<span class="help-block hidden"></span>',
                       '</div>',
                    '</div>',

                    '<hr>',

                    '<div class="row">',
                        '<div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 ">',
                            '<label for="location" class="control-label">Location</label>',
                            '<select name="location" class="form-control" id="location">',
                                '<% _(locations).each(function(location) { %>',
                                '<option data-name="location" value="<%= location %>"><%= location %></option>',
                                '<% }); %>',
                           '</select>',
                        '</div>',
                        '<div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 ">',
                            '<label for="finishDate" class="control-label">Finish date</label>',
                            '<input type="date" class="form-control" id="finishDate" name="finishDate">',
                        '<span class="help-block hidden"></span>',
                        '</div>',
                    '</div>',

                    '<hr>',

                    '<div class="row">',
                        '<div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 ">',
                            '<label for="teachers" class="control-label">Teachers</label>',
                            '<span class="pull-right">x</span>',
                            '<% _(teachers).each(function(teacher) { %>',
                            '<input type="text" class="form-control" name="teachers" id="teachers" value="<%= teacher %>">',
                             '<% }); %>',
                        '</div>',
                        '<div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 ">',
                            '<label for="experts" class="control-label">Experts</label>',
                            '<span class="pull-right">x</span>',
                            '<input type="text" class="form-control" name="experts" id="experts">',
                        '<span class="help-block hidden"></span>',
                        '</div>',
                    '</div>',

                    '<hr>',

                    '<div class="text-center"><span class="glyphicon glyphicon-ok-sign icon" id="save"></span>',
                    '<span class="glyphicon glyphicon-remove-sign icon" id="cancel"></span></div>',
                '</section>',
            '</section>'
].join(''));