templates.groupInfoViewTpl = _.template([
    '<div class="group_coordination">',
        '<h3>Group coordination:</h3>',
        '<table class="tg">',
            '<tr>',
                '<th class="tg-h"></th>',
                '<th class="tg-h"></th>',
            '</tr>',
            '<tr>',
                '<td class="tg-d">Teacher</td>',
                '<td class="tg-d"><%= teachers[0] %></td>',
            '</tr>',
            '<tr>',
                '<td class="tg-d">Expert</td>',
                '<td class="tg-d"><%= experts[0] %></td>',
            '</tr>',
        '</table>',
    '</div>',
    '<div class="group_info">',
        '<h3>Group info:</h3>',
        '<table class="tg">',
            '<tr>',
                '<th class="tg-h"></th>',
                '<th class="tg-h"></th>',
            '</tr>',
            '<tr>',
                '<td class="tg-d">Date start:</td>',
                '<td class="tg-d"><%= startDate %></td>',
            '</tr>',
            '<tr>',
                '<td class="tg-d">Date finish:</td>',
                '<td class="tg-d"><%= finishDate %></td>',
            '</tr>',
        '</table>',
    '</div>'
].join(''));