templates.groupEditCreate = _.template([
   '<section class="modal-window <%= isCreate? \'create\' : \'\'%>">',
                '<section class="form-inline form-wrapper container">',
                    '<div class="row">',
                        '<div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                            '<div class="row">',
                                '<div class="form-group col-xs-12">',
'                                    <label for="name" class="control-label">Group name</label>',
'                                    <input type="text" class="form-control" id="name" name="name" value="<%= name %>">',
                                '</div>',
'                                   <% if (!isCreate) { %>', 
'                                   <div class="form-group col-xs-12 stage-wrapper">',
'                                       <label for="stage" class="control-label">Current stage</label>',
'                                       <select class="form-control" name="stage" id="stage">',
'                                       <% _(stages).each(function(thisStage) { %>',
'                                       <option data-name="stage" value="<%= thisStage %>" <%= thisStage === stage ? \'selected\' : \'\' %> > <%= thisStage %> </option>',
'                                       <% }); %>',
'                                       </select>',
    '                               </div>',
'                                   <% }; %>',
                            ' </div>',
                       ' </div>',

                        '<div class="form-group budgetOptions col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 ">',
                            '<label for="budgetOptions" class="control-label">Budget owner</label>',
                            '<div class="btn-group pull-right" id="budgetOptions">',
                                '<button class="btn btn-default budget-option <%= budgetOwner !==  \'OpenGroup\' ? \'active\' : \'\'%>" data-value="SoftServe">SoftServe</button>',
                                '<button class="btn btn-default budget-option <%= budgetOwner ===  \'OpenGroup\' ? \'active\' : \'\'%>" data-value="OpenGroup">OpenGroup</button>',
                            '</div>',
                        '</div>',
                    '</div>',

                   ' <hr>',

                    '<div class="row">',
                        '<div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 ">',
                            '<label for="direction" class="control-label">Direction</label>',
                           ' <select class="form-control" name="direction" id="direction">',
                                '<option selected="true" disabled="disabled"></option>',
                                '<% _(directions).each(function(thisDirection) { %>',
                                '<option data-name="direction" value="<%= thisDirection %>" <%= thisDirection === direction ? \'selected\' : \'\' %> > <%= thisDirection %> </option>',
                                '<% }); %>',
                            '</select>',
                        '</div>',
                        '<div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 calendar-wrapper">',
                            '<label for="startDate" class="control-label">Start date</label>',
                            '<input type="date" class="form-control" id="startDate" name="startDate" value="<%= startDate %>">',
    '                        <span class="fa fa-calendar fa-2x calendar"></span>',
                       '</div>',
                    '</div>',

                    '<div class="row">',
                        '<div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 ">',
                            '<label for="location" class="control-label">Location</label>',
                            '<select name="location" class="form-control" id="location" <%= !app.user.isRole(\'Administrator\') ? \'disabled\' : \'\' %> >',
                                '<% if (!app.user.isRole(\'Administrator\')) { %>',
                                    '<option data-name="location" value="<%= app.user.get(\'location\') %>"><%= app.user.get(\'location\') %></option>',
                                '<% } else { %>',
                                    '<% _(locations).each(function(thisLocation) { %>',
                                    '<option data-name="location" value="<%= thisLocation %>" <%= (thisLocation === location || thisLocation === defaultLocation) ? \'selected\' : \'\'  %> > <%= thisLocation %> </option>',
                                    '<% }); %>',
                                '<% } %>',
                           '</select>',
                        '</div>',
                        '<div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 calendar-wrapper">',
                            '<label for="finishDate" class="control-label">Finish date</label>',
                            '<input type="date" class="form-control" id="finishDate" name="finishDate" value="<%= finishDate %>">',
    '                        <span class="fa fa-calendar fa-2x calendar"></span>',
                        '</div>',
                    '</div>',

                    '<hr>',

                    '<div class="row">',
                        '<div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4">',
                            '<label class="control-label">Teachers</label>',
                            '<div id="teachers" class="pull-right"></div>',
                        '</div>',
                        '<div class="form-group col-xs-6 col-xs-offset-0 col-md-5 col-md-offset-1 col-lg-4 ">',
                            '<label for="experts" class="control-label">Experts</label>',
    '                        <div id="experts" class="pull-right"></div>',
                        '</div>',
                    '</div>',

                    '<div class="text-center button-group">',
                    '<span class="fa fa-check-circle-o fa-3x btn-icon" id="save"></span>',
                    '<span class="fa fa-times-circle-o fa-3x btn-icon" id="cancel"></span></div>',
    '                </div>',
                '</section>',
            '</section>'
].join(''));