templates.scheduleViewTpl = _.template([
    '<table class="tg">',
        '<tr>',
            '<th class="tg-h"></th>',
            '<th class="tg-h"></th>',
        '</tr>',
        '<tr>',
            '<td class="tg-d">Group</td>',
            '<td class="tg-d"><%= name %></td>',
        '</tr>',
        '<tr>',
            '<td class="tg-d">Start:</td>',
            '<td class="tg-d"><%= startDate %></td>',
        '</tr>',
        '<tr>',
            '<td class="tg-d">Finish:</td>',
            '<td class="tg-d"><%= finishDate %></td>',
        '</tr>',
    '</table>',
].join(''));