templates.studentListViewTpl = _.template([
    '<thead>',
        '<tr>',
            '<td>Name</td>',
            '<td>Photo</td>',
            '<td>English level</td>',
        '</tr>',
    '</thead>',
    '<tbody class = "tableBodyStudents">',
    	'<% _.each(students, function (student) { %>',
	    	'<tr>',
		    '<td><%= student.name %></td>',
		    '<% if ("avatar" in student ) { %>',
		   		'<td><%= student.avatar %></td>',
		    '<% } else { %>',
		    	'<td><img class="photo img-circle" src="/img/default-photo.png"/></td>',
		    '<% } %>',
		    '<td><%= student.englishLevel %></td>',
	   		'</tr>',
	   		'<% }); %>',
    '</tdoby>',
].join(''));

templates.studentListModalViewTpl = _.template([
	'<div>',
		'<h2>Student list</h2>',
		'<button class = "fa fa-plus-square-o fa-4x create"></button>',
	'</div>',
	'<table>',
    '<thead>',
        '<tr>',
            '<td>Name</td>',
            '<td>Photo</td>',
            '<td>English level</td>',
            '<td></td>',
            '<td></td>',
            '<td></td>',
        '</tr>',
    '</thead>',
    '<tbody class = "tableBodyStudents">',
    	'<% _.each(students, function (student) { %>',
	    	'<tr>',
		    '<td><%= student.name %></td>',
		    '<% if ("avatar" in student ) { %>',
		   		'<td><%= student.avatar %></td>',
		    '<% } else { %>',
		    	'<td><img class="photo img-circle" src="/img/default-photo.png"/></td>',
		    '<% } %>',
		    '<td><%= student.englishLevel %></td>',
	   		'<td>CV<img class = "cvDownload" src="" alt=""/></td>',
	   		'<td>Edit<img class = "editStudent" src="" alt="" /></td>',
	   		'<td>Delete<img class = "deleteStudent" src="" alt="" /></td>',
	   		'</tr>',
	   		'<% }); %>',
    '</tdoby>',
    '</table>',
    '<button class = "fa fa-times-circle-o fa-3x btn-icon"></button>',
].join(''));