templates.scheduleViewTpl = _.template([
    '<div class="Table">',
    '<div class="Title"></div>',
    '<div class="Heading">',
        '<div class="Cell null"></div>',
        '<div class="Cell monday">Monday</div>',
        '<div class="Cell tuesday">Tuesday</div>',
        '<div class="Cell wednesday">Wednesday</div>',
        '<div class="Cell thursday">Thursday</div>',
        '<div class="Cell friday">Friday</div>',
    '</div>',
   '<div class="Row nine">',
        '<div class="HeadingCell">9:00</div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
    '</div>',
    '<div class="Row nine-half">',
        '<div class="HeadingCell">9:30</div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
    '</div>',
     '<div class="Row ten">',
        '<div class="HeadingCell">10:00</div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
    '</div>',
    '<div class="Row ten-half">',
        '<div class="HeadingCell">10:30</div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
    '</div>',
    '<div class="Row eleven">',
        '<div class="HeadingCell">11:00</div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
    '</div>',
    '<div class="Row eleven-half">',
        '<div class="HeadingCell">11:30</div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
    '</div>',
    '<div class="Row twelve">',
        '<div class="HeadingCell">12:00</div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
        '<div class="Cell"></div>',
    '</div>',
'</div>'
].join(''));